### ISSUE TITLE
Align configuration page with Beautytips module

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/beautytips_node#2]
While the configuration pages of the required *Beautytips* module are in the *Content authoring* section (`admin/config/content/beautytips`), the config pages of *Beautytips Node* are in the *User interface* section (`admin/config/user-interface/beautytips/node-settings`). I'd suggest to move the config pages of *Beautytips Node* also to the *Content authoring* section.

**Comment by Graham-72** [comment]
I agree - fixed.

**Comment by olafgrabienski** [comment]
Thanks, code looks good! (Let me know if -- or when -- you want changes to be tested.)

**Comment by olafgrabienski** [comment]
Tested: the configuration page is now in the *Content authoring* section! (Closing the issue.)
